version: '3.8'

services:
  keydb-master1:
    image: eqalpha/keydb
    container_name: keydb-master1
    command: keydb-server /etc/keydb/keydb.conf
    ports:
      - "6379:6379"
    volumes:
      - ./master1.conf:/etc/keydb/keydb.conf
      - keydb-master1-data:/data
    cap_add:
      - NET_ADMIN

  keydb-master2:
    image: eqalpha/keydb
    container_name: keydb-master2
    command: keydb-server /etc/keydb/keydb.conf
    ports:
      - "6380:6379"
    volumes:
      - ./master2.conf:/etc/keydb/keydb.conf
      - keydb-master2-data:/data
    depends_on:
      - keydb-master1
    cap_add:
      - NET_ADMIN

  keydb-replica:
    image: eqalpha/keydb
    container_name: keydb-replica
    command: keydb-server /etc/keydb/keydb.conf
    ports:
      - "6381:6379"
    volumes:
      - ./replica.conf:/etc/keydb/keydb.conf
      - keydb-replica-data:/data
    depends_on:
      - keydb-master1
    cap_add:
      - NET_ADMIN

  redis-exporter-m1:
    image: oliver006/redis_exporter
    container_name: redis-exporter-m1
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis://keydb-master1:6379"

  redis-exporter-m2:
    image: oliver006/redis_exporter
    container_name: redis-exporter-m2
    ports:
      - "9122:9121"
    environment:
      REDIS_ADDR: "redis://keydb-master2:6379"

  redis-exporter-replica:
    image: oliver006/redis_exporter
    container_name: redis-exporter-replica
    ports:
      - "9123:9121"
    environment:
      REDIS_ADDR: "redis://keydb-replica:6379"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
  
  # alertmanager:
  #   image: prom/alertmanager
  #   container_name: alertmanager
  #   ports:
  #     - "9093:9093"
  #   volumes:
  #     - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana             
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  
volumes:
  keydb-master1-data:
  keydb-master2-data:
  keydb-replica-data:
  grafana-storage:
