version: '3.8'

services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres_container
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres_password
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5433:5432"

  # redis:
  #   image: redis:latest
  #   container_name: redis_container
  #   ports:
  #     - "6379:6379"
      
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb_container
    ports:
      - "6380:6379"