port 0
tls-port 6379

tls-cert-file /etc/keydb/certs/master3.crt
tls-key-file /etc/keydb/certs/master3.key
tls-ca-cert-file /etc/keydb/certs/keydb-ca.crt

tls-auth-clients yes



multi-master yes
active-replica yes

replicaof keydb-master2 6379


requirepass YourStrongPassword

user default on >YourStrongPassword ~* +@all
