port 0
tls-port 6379

tls-cert-file /etc/keydb/certs/master1.crt
tls-key-file /etc/keydb/certs/master1.key
tls-ca-cert-file /etc/keydb/certs/keydb-ca.crt

tls-auth-clients yes


multi-master yes
active-replica yes

replicaof keydb-master3 6379


requirepass YourStrongPassword

user default on >YourStrongPassword ~* +@all
