version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
  
  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka_exporter
    command:
      - --kafka.server=host.docker.internal:9092
      - --group.filter=.*
      - --topic.filter=.*
      - --log.level=info
    ports:
      - "9308:9308"
    depends_on:
      - prometheus
