rules:
  - pattern: "kafka.server<type=(.+), name=(.+)PerSec\\w*><>Count"
    name: kafka_$1_$2_total
    type: COUNTER
  - pattern: "kafka.server<type=(.+), name=(.+)><>(Count|Value)"
    name: kafka_$1_$2
    type: GAUGE
