bootstrap.servers=localhost:29091,localhost:29092,localhost:29093
security.protocol=SSL

ssl.truststore.location=/Users/nag/kafka-security/kafka-truststore.p12
ssl.truststore.password=changeit
ssl.truststore.type=PKCS12

If using client authentication (optional)
ssl.keystore.location=/Users/nag/kafka-security/client.p12
ssl.keystore.password=changeit
ssl.keystore.type=PKCS12
ssl.key.password=changeit
