security.protocol=SSL

ssl.truststore.location=/Users/nag/kkc/security/kafka-security/certs/kafka-truststore.p12
ssl.truststore.password=changeit
ssl.truststore.type=PKCS12


ssl.keystore.location=/Users/nag/kkc/security/kafka-security/certs/client.p12
ssl.keystore.password=changeit
ssl.keystore.type=PKCS12