bootstrap.servers=localhost:29091,localhost:29092,localhost:29093
security.protocol=SSL

# If you have client authentication enabled, set these; otherwise omit or comment out
# ssl.keystore.location=/path/to/client.p12
# ssl.keystore.password=changeit
# ssl.keystore.type=PKCS12
# ssl.key.password=changeit

ssl.truststore.location=/Users/nag/kafka-security/kafka-truststore.p12
ssl.truststore.password=changeit
ssl.truststore.type=PKCS12

key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer
